title: Li-Yang Wang
baseurl: ""
url: "https://liyangwang95.github.io"

# Define Collections
collections:
  projects:
    output: true
    permalink: /projects/:name
  recipes:
    output: true
    permalink: /recipes/:name

plugins:
  - jekyll-sitemap

timezone: Europe/Amsterdam  # CET/CEST